### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by denza**

### CODE REVIEW

**Review by IonicaBizau — CHANGES_REQUESTED** [review]
Can you update the `package.json` like in #1? Thanks!

**Comment by sake92** [comment]
I think he means #2. 😃

**Comment by IonicaBizau** [comment]
Yes, #2. 🙂

**Comment by IonicaBizau** [comment]
@sake92 If you like, you can do it. Btw, there is the Hacktoberfest going on this month, so you can get a t-shirt. Haha! 😁 

https://hacktoberfest.digitalocean.com

**Comment by sake92** [comment]
@IonicaBizau Of course, no problem. I'm on it already...
Who doesn't like freebies? 😆

**Comment by IonicaBizau** [comment]
Thanks, @sake92! 🍰

**Pull request closed without merging**
