### PR TITLE
Added BuVRek and focustube to JS

### PR DESCRIPTION
**Pull request by TheAdnan**

### CODE REVIEW

**Review by IonicaBizau — CHANGES_REQUESTED** [review]
Thanks! Please edit `package.json` as well. :grin:

**Comment by TheAdnan** [comment]
I've edited package.json :)

**Comment by TheAdnan** [comment]
Hi @IonicaBizau , do I need to add anything else? 😃

**Review by IonicaBizau — APPROVED** [review]
Thanks :)

**Pull request merged**
